name: credit-risk
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11.8
  - ipykernel=6.29.5
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - plotly=5.24.1
  - sdv=1.17.4
  - pytorch=2.2.2
  - rdt=1.13.2
  - nbformat=5.10.4
  - catboost=1.2.7
  - ipywidgets=8.1.5
  - mlxtend=0.23.4
  - shap=0.46.0